### ISSUE TITLE
Improper locking error, a lock is not released?

### ISSUE THREAD

**Issue by ryancaicse** [free-sm/geonkick#163]
HI, developers, it seems the lock **geonkick_worker->lock** is never released when **pthread_cond_init(&geonkick_worker->condition_var, NULL) != 0** in the program. Shoule it be a bug? Thanks~
https://github.com/free-sm/geonkick/blob/4f6314366679c5d1bf63ff9d21455ee07a5de323/dsp/src/worker.c#L43-L60

Best,

**Comment by iurienistor** [comment]
pthread_mutex_lock(&geonkick_worker->lock);  yes, is redundant, and probably was left there due to a mistake. Must be removed.

**Comment by iurienistor** [comment]
Thank you for reporting it. Now it is fixed.
