### ISSUE TITLE
Where did the Freq/Pitch envelope go?

### ISSUE THREAD

**Issue by fractalf** [free-sm/geonkick#169]
Is it just me? I've been looking for a way to view the freq/pitch envelope for 30min now after an upgrade to a new version.

Left: old version
Right: new version

![image](https://user-images.githubusercontent.com/5707457/158886302-c21be579-a3bf-4eb4-bd23-6256eb6b15a3.png)

**Comment by iurienistor** [comment]
![158886302-c21be579-a3bf-4eb4-bd23-6256eb6b15a3](https://user-images.githubusercontent.com/56111777/159039219-3bc1db3d-9390-4647-904d-b09e6dfe6d41.png)
@fractalf

**Comment by fractalf** [comment]
Thank you very much @iurienistor !
...it was staring me in the face, but still I couldn't see it ;)
