### ISSUE TITLE
mac build 

### ISSUE THREAD

**Issue by reathance** [free-sm/geonkick#173]
hi! im really new to all the coding stuff and the questions im about to ask might be a bit dumb so excuse me for that
is it possible to build geonkick as a vst3 for mac? ive tried doing that both through terminal and cmake application, but both times got the same error:

CMake Error at /Applications/CMake.app/Contents/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.23/Modules/FindPkgConfig.cmake:99 (find_package_handle_standard_args)
  CMakeLists.txt:191 (find_package)

is there a way to fix that? or is that because of geonkick not being compatible with mac?

**Comment by iurienistor** [comment]
@reathance Geonkick for now is compatible only with GNU/Linux.
