### ISSUE TITLE
Trouble building VST3

### ISSUE THREAD

**Issue by elcalenx** [free-sm/geonkick#175]
Hi! I'm trying to build Geonkick on my Debian testing system. LV2 builds fine, but VST3 fails, with the following output. I *think* I should have all the VST3 build dependencies installed, assuming the info I found was correct...

> [ 92%] Building CXX object 3rdparty/vst3_sdk/pluginterfaces/CMakeFiles/pluginterfaces.dir/base/funknown.cpp.o
/home/ben/Downloads/vst/geonkick/3rdparty/vst3_sdk/pluginterfaces/base/funknown.cpp: In function ‘Steinberg::int32 Steinberg::FUnknownPrivate::atomicAdd(Steinberg::int32&, Steinberg::int32)’:
/home/ben/Downloads/vst/geonkick/3rdparty/vst3_sdk/pluginterfaces/base/funknown.cpp:91:51: error: ‘atomic_int_least32_t’ does not name a type
   91 |         return atomic_fetch_add (reinterpret_cast<atomic_int_least32_t*> (&var), d) + d;
      |                                                   ^~~~~~~~~~~~~~~~~~~~
/home/ben/Downloads/vst/geonkick/3rdparty/vst3_sdk/pluginterfaces/base/funknown.cpp:91:71: error: expected ‘>’ before ‘*’ token
   91 |         return atomic_fetch_add (reinterpret_cast<atomic_int_least32_t*> (&var), d) + d;
      |                                                                       ^
/home/ben/Downloads/vst/geonkick/3rdparty/vst3_sdk/pluginterfaces/base/funknown.cpp:91:71: error: expected ‘(’ before ‘*’ token
   91 |         return atomic_fetch_add (reinterpret_cast<atomic_int_least32_t*> (&var), d) + d;
      |                                                                       ^
      |                                                                       (
/home/ben/Downloads/vst/geonkick/3rdparty/vst3_sdk/pluginterfaces/base/funknown.cpp:91:72: error: expected primary-expression before ‘>’ token
   91 |         return atomic_fetch_add (reinterpret_cast<atomic_int_least32_t*> (&var), d) + d;
      |                                                                        ^
make[2]: *** [3rdparty/vst3_sdk/pluginterfaces/CMakeFiles/pluginterfaces.dir/build.make:104: 3rdparty/vst3_sdk/pluginterfaces/CMakeFiles/pluginterfaces.dir/base/funknown.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:616: 3rdparty/vst3_sdk/pluginterfaces/CMakeFiles/pluginterfaces.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by iurienistor** [comment]
For now I'll close this. If this is still a problem, than I'll reopen and check.
