### ISSUE TITLE
55Hz shows A#1 (should be A1)

### ISSUE THREAD

**Issue by fractalf** [free-sm/geonkick#180]
Hi, 
thank you for a great plugin :)

I noticed that 55Hz shows the wrong note. I did some more checks, but that was the only one I found, but I guess there could be more since the calculation already have one error.

Just a FYI

![geon-bug](https://user-images.githubusercontent.com/5707457/215091660-4194c2ef-e6fd-4947-8618-13ca6d0b00d0.png)

**Comment by iurienistor** [comment]
@fractalf Fixed in this commit, main branch. - https://github.com/free-sm/geonkick/commit/1183cac43970766c0b07261595e491df3c31c053

**Comment by iurienistor** [comment]
There were made additional fixes for this, but this will be released already in 2.10. This should include saving/loading with precision from the preset.
